import { useOutletContext } from "react-router-dom";
import { FiTrash2, FiBell, FiCheckCircle, FiMail, FiCheck } from "react-icons/fi";
import DataTable from "../../components/DataTable";
import ConfirmDialog from "../../components/ConfirmDialog";
import { useState } from "react";
import { useResourceList } from "../../hooks/useResourceList";
import { notificationsApi } from "../../api";
import { useToast, errMsg } from "../../context/ToastContext";
import "../CrudPage/CrudPage.css";
import "./Notifications.css";

export default function Notifications() {
  const [confirmId, setConfirmId] = useState(null);
  const [deleting, setDeleting] = useState(false);
  const toast = useToast();
  const outletCtx = useOutletContext?.() || {};

  const { rows, loading, q, onSearch, pagination, setPage, reload } = useResourceList(notificationsApi);

  const markRead = async (row) => {
    try {
      await notificationsApi.markRead(row.id);
      reload();
      outletCtx.refreshNotifications?.();
    } catch (err) {
      toast.error(errMsg(err, "Failed to update notification."));
    }
  };

  const markAllRead = async () => {
    try {
      await notificationsApi.markAllRead();
      toast.success("All notifications marked as read.");
      reload();
      outletCtx.refreshNotifications?.();
    } catch (err) {
      toast.error(errMsg(err, "Failed to mark all as read."));
    }
  };

  const handleDelete = async () => {
    setDeleting(true);
    try {
      await notificationsApi.remove(confirmId);
      toast.success("Notification deleted.");
      setConfirmId(null);
      reload();
      outletCtx.refreshNotifications?.();
    } catch (err) {
      toast.error(errMsg(err, "Failed to delete notification."));
    } finally {
      setDeleting(false);
    }
  };

  const columns = [
    {
      key: "read",
      label: "",
      width: 40,
      render: (row) => (
        <span className="admx-notif-icon" style={{ color: row.isRead ? "var(--text-muted)" : "var(--primary-light)" }}>
          <FiBell />
        </span>
      ),
    },
    {
      key: "title",
      label: "Notification",
      render: (row) => (
        <div>
          <strong style={{ color: row.isRead ? "var(--text-light)" : "var(--text)" }}>{row.title}</strong>
          {row.body && <span className="admx-cell-sub">{row.body}</span>}
        </div>
      ),
    },
    {
      key: "meta",
      label: "Details",
      render: (row) => (
        <div className="admx-notif-details">
          {row.meta?.email && <span><FiMail /> {row.meta.email}</span>}
          {row.meta?.phone && <span>{row.meta.phone}</span>}
        </div>
      ),
    },
    {
      key: "emailSent",
      label: "Email",
      render: (row) => (
        <span className={`admx-badge ${row.emailSent ? "admx-badge-success" : "admx-badge-muted"}`}>
          {row.emailSent ? "Sent" : "Skipped"}
        </span>
      ),
    },
    {
      key: "createdAt",
      label: "Received",
      render: (row) => new Date(row.createdAt).toLocaleString(),
    },
  ];

  return (
    <div className="admx-page">
      <div className="admx-page-head">
        <div>
          <h1 className="admx-page-title">Notifications</h1>
          <p className="admx-page-subtitle">Full history of alerts generated by visitor activity, such as contact-form submissions.</p>
        </div>
        <div className="admx-quick-actions">
          <button className="admx-btn admx-btn-outline" onClick={markAllRead}>
            <FiCheck /> Mark all read
          </button>
        </div>
      </div>

      <DataTable
        columns={columns}
        rows={rows}
        loading={loading}
        q={q}
        onSearch={onSearch}
        pagination={pagination}
        onPageChange={setPage}
        searchPlaceholder="Search notifications…"
        emptyMessage="No notifications yet."
        actions={(row) => (
          <>
            {!row.isRead && (
              <button className="admx-btn admx-btn-outline admx-btn-sm" onClick={() => markRead(row)} title="Mark as read">
                <FiCheckCircle /> Read
              </button>
            )}
            <button className="admx-btn admx-btn-danger admx-btn-icon admx-btn-sm" onClick={() => setConfirmId(row.id)} title="Delete">
              <FiTrash2 />
            </button>
          </>
        )}
      />

      <ConfirmDialog
        open={!!confirmId}
        onClose={() => setConfirmId(null)}
        onConfirm={handleDelete}
        loading={deleting}
        message="This will permanently delete this notification. This cannot be undone."
      />
    </div>
  );
}
